export const FILE_UPLOAD_POLICY = {
  ANY: "ANY",
  AVATAR: "AVATAR",
  COURSE_COVER: "COURSE_COVER",
  COURSE_ITEM: "COURSE_ITEM",
  SUPPORT_ATTACHMENT: "SUPPORT_ATTACHMENT",
  PAYMENT_RECEIPT: "PAYMENT_RECEIPT",
  PAYMENT_EVIDENCE: "PAYMENT_EVIDENCE",
} as const;

export type FileUploadPolicyId =
  (typeof FILE_UPLOAD_POLICY)[keyof typeof FILE_UPLOAD_POLICY];

export const FILE_UPLOAD_POLICY_MAX_SIZE_BYTES: Record<FileUploadPolicyId, number> = {
  [FILE_UPLOAD_POLICY.ANY]: 50 * 1024 * 1024,
  [FILE_UPLOAD_POLICY.AVATAR]: 5 * 1024 * 1024,
  [FILE_UPLOAD_POLICY.COURSE_COVER]: 20 * 1024 * 1024,
  [FILE_UPLOAD_POLICY.COURSE_ITEM]: 50 * 1024 * 1024,
  [FILE_UPLOAD_POLICY.SUPPORT_ATTACHMENT]: 10 * 1024 * 1024,
  [FILE_UPLOAD_POLICY.PAYMENT_RECEIPT]: 5 * 1024 * 1024,
  [FILE_UPLOAD_POLICY.PAYMENT_EVIDENCE]: 10 * 1024 * 1024,
};
