export const GENERAL_SUBSCRIPTION_UPDATE_TYPES = {
  NOTIFICATION: "NOTIFICATION",
  GENERAL_COUNTS: "GENERAL_COUNTS",
  GLOBAL_ANOUNCEMENT: "GLOBAL_ANOUNCEMENT",
  SUPPORT_UPDATE: "SUPPORT_UPDATE",
} as const;

export type GeneralSubscriptionUpdateType =
  (typeof GENERAL_SUBSCRIPTION_UPDATE_TYPES)[keyof typeof GENERAL_SUBSCRIPTION_UPDATE_TYPES];
