export const APP_SHELL_ROUTES = {
  login: "/login",
  resetPassword: "/reset-password",
  dashboard: "/dashboard",
  courses: "/courses",
  courseDetail: "/courses/:courseId",
  more: "/more",
  moreAbout: "/more/about",
  morePrivacyPolicy: "/more/privacy-policy",
  moreTermsOfUse: "/more/terms-of-use",
  moreSystemSettings: "/more/system-settings",
  moreAdminNotification: "/more/admin-notification",
  notifications: "/notifications",
  payments: "/payments",
  paymentZarinPalCallback: "/payment/zarinpal/callback",
  profile: "/profile",
  support: "/support",
  supportFaq: "/support/faq",
  supportTickets: "/support/tickets",
  users: "/users",
  usersManagement: "/users-management",
  home: "/",
} as const;
