import { Field, GraphQLISODateTime, ID, Int, ObjectType } from "@nestjs/graphql";
import { Types } from "mongoose";

import { CourseReviewVisibility, UserRole } from "../../../../enums";
import { PaginationCursorResponse } from "../../../../common/pagination/response";
import { UserMinimalGqlResponse } from "../../../user/graphql/responses/common";

@ObjectType()
export class CourseReviewModerationGqlResponse {
  @Field(() => CourseReviewVisibility, {
    description: "Moderation visibility for this content",
  })
  visibility: CourseReviewVisibility;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the content was hidden",
  })
  hiddenAt?: Date;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that hid the content",
  })
  hiddenByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that hid the content",
  })
  hiddenByUser?: UserMinimalGqlResponse;

  @Field({
    nullable: true,
    description: "Internal moderation note",
  })
  hiddenReason?: string;
}

@ObjectType()
export class CourseReviewRatingGqlResponse {
  @Field(() => Int, { description: "Star rating from 1 to 5" })
  stars: number;

  @Field({ nullable: true, description: "Optional review comment" })
  comment?: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the rating was first submitted",
  })
  ratedAt: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the rating was last updated",
  })
  updatedAt?: Date;

  @Field(() => CourseReviewModerationGqlResponse, {
    description: "Rating moderation metadata",
  })
  moderation: CourseReviewModerationGqlResponse;
}

@ObjectType()
export class CourseReviewMessageGqlResponse {
  @Field({ description: "Stable message key generated by the database" })
  key: string;

  @Field({ description: "Message body" })
  body: string;

  @Field(() => ID, { description: "Sender user ID" })
  senderUserId: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal sender user information",
  })
  senderUser?: UserMinimalGqlResponse;

  @Field(() => GraphQLISODateTime, { description: "Date when the message was sent" })
  sentAt: Date;

  @Field(() => CourseReviewModerationGqlResponse, {
    description: "Message moderation metadata",
  })
  moderation: CourseReviewModerationGqlResponse;
}

@ObjectType()
export class CourseReviewUserSnapshotGqlResponse {
  @Field({ description: "Stored full name snapshot" })
  fullName: string;

  @Field({ description: "Stored username snapshot" })
  username: string;

  @Field(() => ID, {
    nullable: true,
    description: "Stored avatar file ID snapshot",
  })
  avatarFileId?: Types.ObjectId;
}

@ObjectType()
export class CourseReviewCourseSnapshotGqlResponse {
  @Field({ description: "Stored course title snapshot" })
  title: string;
}

@ObjectType()
export class CourseReviewListGqlResponse {
  @Field(() => ID, { description: "Course review thread ID" })
  id: Types.ObjectId;

  @Field(() => ID, { description: "Review owner user ID" })
  userId: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal review owner information",
  })
  user?: UserMinimalGqlResponse;

  @Field(() => ID, { description: "Course ID" })
  courseId: Types.ObjectId;

  @Field(() => ID, {
    nullable: true,
    description: "Linked user course enrollment ID, when the reviewer purchased the course",
  })
  userCourseId?: Types.ObjectId;

  @Field(() => CourseReviewUserSnapshotGqlResponse, {
    description: "Stored review owner snapshot",
  })
  userSnapshot: CourseReviewUserSnapshotGqlResponse;

  @Field(() => CourseReviewCourseSnapshotGqlResponse, {
    description: "Stored course snapshot",
  })
  courseSnapshot: CourseReviewCourseSnapshotGqlResponse;

  @Field(() => CourseReviewModerationGqlResponse, {
    description: "Review thread moderation metadata",
  })
  moderation: CourseReviewModerationGqlResponse;

  @Field(() => CourseReviewRatingGqlResponse, {
    nullable: true,
    description: "Course rating, if submitted",
  })
  rating?: CourseReviewRatingGqlResponse;

  @Field(() => [CourseReviewMessageGqlResponse], {
    description: "Full Q&A message thread",
  })
  messages: CourseReviewMessageGqlResponse[];

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the review thread was created",
  })
  createdAt?: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the review thread was last updated",
  })
  updatedAt?: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the review thread was soft deleted",
  })
  deletedAt?: Date;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that created the review thread",
  })
  createdByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that created the review thread",
  })
  createdByUser?: UserMinimalGqlResponse;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that last updated the review thread",
  })
  updatedByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that last updated the review thread",
  })
  updatedByUser?: UserMinimalGqlResponse;

  @Field(() => ID, {
    nullable: true,
    description: "User ID that soft deleted the review thread",
  })
  deletedByUserId?: Types.ObjectId;

  @Field(() => UserMinimalGqlResponse, {
    nullable: true,
    description: "Minimal user that soft deleted the review thread",
  })
  deletedByUser?: UserMinimalGqlResponse;
}

@ObjectType()
export class CourseReviewListPaginatedCursorGqlResponse {
  @Field(() => [CourseReviewListGqlResponse], {
    description: "Full course review list for SUPER_ADMIN",
  })
  items: CourseReviewListGqlResponse[];

  @Field(() => PaginationCursorResponse, {
    description: "Pagination metadata",
  })
  pagination: PaginationCursorResponse;
}
