import {
  Field,
  GraphQLISODateTime,
  ID,
  Int,
  ObjectType,
} from "@nestjs/graphql";
import { Types } from "mongoose";

import { PaginationCursorResponse } from "../../../../common/pagination/response";
import { CourseReviewRatingSummaryGqlResponse } from "./course-review-list.gql.response";

@ObjectType()
export class UserCourseReviewAuthorGqlResponse {
  @Field({ description: "Review author's first name from the user profile" })
  firstName: string;
}

@ObjectType()
export class UserCourseReviewRatingGqlResponse {
  @Field(() => Int, { description: "Star rating from 1 to 5" })
  stars: number;

  @Field({ nullable: true, description: "Optional review comment" })
  comment?: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the rating was first submitted",
  })
  ratedAt: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the rating was last updated",
  })
  updatedAt?: Date;
}

@ObjectType()
export class UserCourseReviewMessageSenderGqlResponse {
  @Field({ description: "Message sender first name from the user profile" })
  firstName: string;

  @Field({
    description:
      "Whether the message was sent by support staff rather than the review author",
  })
  isSupport: boolean;
}

@ObjectType()
export class UserCourseReviewMessageGqlResponse {
  @Field({ description: "Stable message key generated by the database" })
  key: string;

  @Field({ description: "Message body" })
  body: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the message was sent",
  })
  sentAt: Date;

  @Field(() => UserCourseReviewMessageSenderGqlResponse, {
    description: "Sanitized sender information",
  })
  sender: UserCourseReviewMessageSenderGqlResponse;
}

@ObjectType()
export class UserCourseReviewListGqlResponse {
  @Field(() => ID, { description: "Course review thread ID" })
  id: Types.ObjectId;

  @Field({
    description: "Whether this review thread belongs to the current user",
  })
  isMine: boolean;

  @Field(() => UserCourseReviewAuthorGqlResponse, {
    description: "Sanitized review author information",
  })
  author: UserCourseReviewAuthorGqlResponse;

  @Field(() => UserCourseReviewRatingGqlResponse, {
    nullable: true,
    description: "Rating visible when its moderation visibility is PUBLIC",
  })
  rating?: UserCourseReviewRatingGqlResponse;

  @Field(() => [UserCourseReviewMessageGqlResponse], {
    description:
      "Public follow-up comments and support messages with PUBLIC moderation",
  })
  messages: UserCourseReviewMessageGqlResponse[];

  @Field({
    description:
      "Whether the current user is blocked from submitting updates because the review thread is hidden",
    defaultValue: false,
  })
  isSubmissionBlocked: boolean;

  @Field({
    description:
      "Whether the current user's rating exists but is hidden from their view",
    defaultValue: false,
  })
  isRatingHidden: boolean;
}

@ObjectType()
export class UserCourseReviewListPaginatedCursorGqlResponse {
  @Field(() => [UserCourseReviewListGqlResponse], {
    description: "Course reviews visible to the current END_USER",
  })
  items: UserCourseReviewListGqlResponse[];

  @Field(() => PaginationCursorResponse, {
    description: "Pagination metadata",
  })
  pagination: PaginationCursorResponse;

  @Field(() => CourseReviewRatingSummaryGqlResponse, {
    description:
      "Aggregated public rating summary excluding hidden reviews and hidden ratings",
  })
  summary: CourseReviewRatingSummaryGqlResponse;
}
