import { Field, GraphQLISODateTime, ID, Int, ObjectType } from "@nestjs/graphql";
import { Types } from "mongoose";

import { PaginationCursorResponse } from "../../../../common/pagination/response";

@ObjectType()
export class UserCourseReviewAuthorGqlResponse {
  @Field({ description: "Review author's first name only" })
  firstName: string;
}

@ObjectType()
export class UserCourseReviewRatingGqlResponse {
  @Field(() => Int, { description: "Star rating from 1 to 5" })
  stars: number;

  @Field({ nullable: true, description: "Optional review comment" })
  comment?: string;

  @Field(() => GraphQLISODateTime, {
    description: "Date when the rating was first submitted",
  })
  ratedAt: Date;

  @Field(() => GraphQLISODateTime, {
    nullable: true,
    description: "Date when the rating was last updated",
  })
  updatedAt?: Date;
}

@ObjectType()
export class UserCourseReviewMessageSenderGqlResponse {
  @Field({ description: "Message sender first name or support label" })
  firstName: string;

  @Field({
    description:
      "Whether the message was sent by support staff rather than the review author",
  })
  isSupport: boolean;
}

@ObjectType()
export class UserCourseReviewMessageGqlResponse {
  @Field({ description: "Stable message key generated by the database" })
  key: string;

  @Field({ description: "Message body" })
  body: string;

  @Field(() => GraphQLISODateTime, { description: "Date when the message was sent" })
  sentAt: Date;

  @Field(() => UserCourseReviewMessageSenderGqlResponse, {
    description: "Sanitized sender information",
  })
  sender: UserCourseReviewMessageSenderGqlResponse;
}

@ObjectType()
export class UserCourseReviewListGqlResponse {
  @Field(() => ID, { description: "Course review thread ID" })
  id: Types.ObjectId;

  @Field({
    description: "Whether this review thread belongs to the current user",
  })
  isMine: boolean;

  @Field(() => UserCourseReviewAuthorGqlResponse, {
    description: "Sanitized review author information",
  })
  author: UserCourseReviewAuthorGqlResponse;

  @Field(() => UserCourseReviewRatingGqlResponse, {
    nullable: true,
    description: "Visible rating for this review, if any",
  })
  rating?: UserCourseReviewRatingGqlResponse;

  @Field(() => [UserCourseReviewMessageGqlResponse], {
    description:
      "Public follow-up comments from the review author plus support messages visible only on the current user's own review",
  })
  messages: UserCourseReviewMessageGqlResponse[];
}

@ObjectType()
export class UserCourseReviewListPaginatedCursorGqlResponse {
  @Field(() => [UserCourseReviewListGqlResponse], {
    description: "Course reviews visible to the current END_USER",
  })
  items: UserCourseReviewListGqlResponse[];

  @Field(() => PaginationCursorResponse, {
    description: "Pagination metadata",
  })
  pagination: PaginationCursorResponse;
}
