export const APP_SETTING_KEY = {
  PAYMENT_CARDS: "PAYMENT_CARDS",
  PAYMENT_METHODS: "PAYMENT_METHODS",
  USDT_WALLETS: "USDT_WALLETS",
  USDT_IRT_RATE: "USDT_IRT_RATE",
  ZARINPAL_CONFIG: "ZARINPAL_CONFIG",
  EMAIL_SMTP_CONFIG: "EMAIL_SMTP_CONFIG",
} as const;

export const PAYMENT_CHECKOUT_SETTING_KEYS = [
  APP_SETTING_KEY.PAYMENT_CARDS,
  APP_SETTING_KEY.PAYMENT_METHODS,
  APP_SETTING_KEY.USDT_WALLETS,
  APP_SETTING_KEY.USDT_IRT_RATE,
] as const;
