// This file is auto-generated by scripts/generate-build-versions.mjs — do not edit manually.

export const WEB_VERSION = "1.0.17";
export const API_VERSION = "1.0.16";
export const ANDROID_APP_VERSION = "2.0.15";
