export enum GeneralSubscriptionUpdateType {
  NOTIFICATION = "NOTIFICATION",
  GENERAL_COUNTS = "GENERAL_COUNTS",
  SUPPORT_UPDATE = "SUPPORT_UPDATE",
  GENERAL_ANOUNCEMENT = "GENERAL_ANOUNCEMENT",
}
